<a href="https://colab.research.google.com/github/nataliepham6720/autobounds_exp/blob/main/Education_vs_Voting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
# !pip install pyscipopt==4.3.0 --extra-index-url https://zenodo.org/api/files/kotdvw5srpqto3xslzj1

!pip install git+https://github.com/duarteguilherme/autobounds

  Cloning https://github.com/duarteguilherme/autobounds to /tmp/pip-req-build-bt0c6nku
  Running command git clone --filter=blob:none --quiet https://github.com/duarteguilherme/autobounds /tmp/pip-req-build-bt0c6nku
  Resolved https://github.com/duarteguilherme/autobounds to commit 13b7520febdfe59d29c917a4501e69fde5f78c6d
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done


## Autobound simulation

In [25]:
from autobounds import *
import pandas
import numpy as np

In [26]:
confounding_model = DAG("D -> Y, X -> D, X -> Y, U -> D, U -> Y", unob="U")
confounding_problem = causalProblem(confounding_model)
confounding_problem.set_ate(ind="D", dep="Y")

In [27]:
# -------------------------------------------------------------------
strata_list = [
    ("00", "0000", 0.074576212961429),
    ("01", "0001", 0.0301702777607751),
    ("01", "0101", 0.186607173274612),
    ("01", "1101", 0.00798467737923486),
    ("10", "0010", 0.348297597134471),
    ("10", "1001", 0.134412818663854),
    ("10", "1010", 0.0480346194425266),
    ("10", "1111", 0.0940165222917155),
    ("11", "1100", 0.0345830964246296),
    ("11", "1101", 0.041317004666752),
]

df = pandas.DataFrame(strata_list, columns=["D_type", "Y_type", "prob"])

N = 10000   # simulation size

# sample D and Y according to the strata list
stratum_idx = np.random.choice(df.index, size=N, p=df["prob"].values)
sim = df.loc[stratum_idx].reset_index(drop=True)

# sample X ~ Bernoulli(0.6)
sim["X"] = np.random.binomial(1, 0.6, size=N)

# compute factual D and Y based on principal strata definitions
def compute_D(D_type, X):
    # D_type = d0d1
    return int(D_type[X])

def compute_Y(Y_type, D, X):
    # Y_type = y00 y01 y10 y11  (4 bits)
    # index = 2*D + X
    idx = 2 * D + X
    return int(Y_type[idx])

# factual D
sim["D"] = [compute_D(dt, x) for dt, x in zip(sim["D_type"], sim["X"])]

# factual Y
sim["Y"] = [compute_Y(yt, d, x)
            for yt, d, x in zip(sim["Y_type"], sim["D"], sim["X"])]

# store factual observed data
confounding_data = sim[["X", "D", "Y"]]

In [28]:
# solve without monotone response constraints
confounding_problem.read_data(raw=confounding_data, inference=True)
confounding_problem.solve(ci=True, nsamples=10)

Solving for point estimate bounds...
Point estimates

Dual: [-0.1679, 0.8321]
Primal: [-0.1679, 0.8321]
Generating samples:

Estimating CI: 


100%|██████████| 10/10 [00:05<00:00,  1.71it/s]

95% Confidence intervals. Lower: -0.1746533318578115,  Upper: 0.8383178455386135


{'point lb dual': -0.1679,
 'point ub dual': 0.8321,
 'point lb primal': -0.1679,
 'point ub primal': 0.8321,
 '2.5% lb bounds': np.float64(-0.1746533318578115),
 '97.5% ub bounds': np.float64(0.8383178455386135),
 '1% lb bounds': np.float64(-0.1756388370373526),
 '99% ub bounds': np.float64(0.8388294462113562)}

In [21]:
import numpy as np
import pandas as pd
import cvxpy as cp

# --------------------------
# DAG and causal problem setup
# --------------------------
class DAG:
    def __init__(self, graph_str, unob="U"):
        self.edges = graph_str
        self.V = [v.strip() for v in set("".join([s.replace("->", ",") for s in graph_str.split(",")]).split()) if v.strip() != unob]
        self.unob = unob

# Minimal causalProblem skeleton
class causalProblem:
    def __init__(self, dag):
        self.dag = dag
        self.parameters = []
        self.constraints = []
        self.estimand = None

    def set_ate(self, ind, dep):
        # estimand variable
        self.estimand = "objvar"

    def load_data(self, data, cond=[]):
        # ensure cond_data is always a dataframe
        cond_data = data[cond].reset_index(drop=True) if len(cond) > 0 else pd.DataFrame()
        self.data = data
        self.cond_data = cond_data

    def write_lp(self):
        """Build explicit LP for bounds using cvxpy"""
        n = self.data.shape[0]
        # one variable per row (P(row))
        p = cp.Variable(n)
        constraints = []

        # Probabilities sum to 1
        constraints.append(cp.sum(p) == 1)
        # Each probability between 0 and 1
        constraints += [p >= 0, p <= 1]

        # Add constraints for observed D, Y, X frequencies
        for col in ["D","Y","X"]:
            freq = self.data.groupby(col).size() / n
            for val, f in freq.items():
                idxs = self.data.index[self.data[col]==val].tolist()
                constraints.append(cp.sum(cp.vstack([p[i] for i in idxs])) == f)

        # Objective: ATE = E[Y|do(D=1)] - E[Y|do(D=0)]
        y_do1 = self.data[self.data["D"]==1]["Y"].values
        y_do0 = self.data[self.data["D"]==0]["Y"].values

        p_do1_idx = self.data.index[self.data["D"]==1].tolist()
        p_do0_idx = self.data.index[self.data["D"]==0].tolist()

        ate_expr = cp.sum(cp.vstack([p[i]*self.data.loc[i,"Y"] for i in p_do1_idx])) \
                   - cp.sum(cp.vstack([p[i]*self.data.loc[i,"Y"] for i in p_do0_idx]))

        return p, constraints, ate_expr

# --------------------------
# Create DAG and problem
# --------------------------
confounding_model = DAG("D -> Y, X -> D, X -> Y, U -> D, U -> Y", unob="U")
confounding_problem = causalProblem(confounding_model)
confounding_problem.set_ate(ind="D", dep="Y")

# --------------------------
# Simulate strata data
# --------------------------
strata_list = [
    ("00", "0000", 0.074576212961429),
    ("01", "0001", 0.0301702777607751),
    ("01", "0101", 0.186607173274612),
    ("01", "1101", 0.00798467737923486),
    ("10", "0010", 0.348297597134471),
    ("10", "1001", 0.134412818663854),
    ("10", "1010", 0.0480346194425266),
    ("10", "1111", 0.0940165222917155),
    ("11", "1100", 0.0345830964246296),
    ("11", "1101", 0.041317004666752),
]
df = pd.DataFrame(strata_list, columns=["D_type", "Y_type", "prob"])

N = 10000
# sample D_type/Y_type according to strata
stratum_idx = np.random.choice(df.index, size=N, p=df["prob"].values)
sim = df.loc[stratum_idx].reset_index(drop=True)

# sample X ~ Bernoulli(0.6)
sim["X"] = np.random.binomial(1, 0.6, size=N)

# compute factual D and Y
def compute_D(D_type, X):
    return int(D_type[X])

def compute_Y(Y_type, D, X):
    idx = 2*D + X
    return int(Y_type[idx])

sim["D"] = [compute_D(dt,x) for dt,x in zip(sim["D_type"], sim["X"])]
sim["Y"] = [compute_Y(yt,d,x) for yt,d,x in zip(sim["Y_type"], sim["D"], sim["X"])]

confounding_data = sim[["X","D","Y"]]
confounding_problem.load_data(confounding_data)

# --------------------------
# Build LP and solve
# --------------------------
p_var, lp_constraints, ate_expr = confounding_problem.write_lp()

# Lower bound (minimize ATE)
prob_min = cp.Problem(cp.Minimize(ate_expr), lp_constraints)
prob_min.solve(solver=cp.GLPK)
print("LOWER BOUND:")
print("Primal:", prob_min.value)
print("Duals:")
for c in lp_constraints:
    try:
        print(c.dual_value)
    except:
        print("None")

# Upper bound (maximize ATE)
prob_max = cp.Problem(cp.Maximize(ate_expr), lp_constraints)
prob_max.solve(solver=cp.GLPK)
print("\nUPPER BOUND:")
print("Primal:", prob_max.value)
print("Duals:")
for c in lp_constraints:
    try:
        print(c.dual_value)
    except:
        print("None")


/usr/local/lib/python3.12/dist-packages/cvxpy/problems/problem.py:158: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
/usr/local/lib/python3.12/dist-packages/cvxpy/problems/problem.py:164: UserWarning: Constraint #3 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
/usr/local/lib/python3.12/dist-packages/cvxpy/problems/problem.py:164: UserWarning: Constraint #5 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
/usr/local/lib/python3.12/dist-packages/cvxpy/problems/problem.py:164: UserWarning: Constraint #8 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.


LOWER BOUND:
Primal: -0.41479999999999984
Duals:
-0.0
[-0. -0. -0. ... -0. -0.  2.]
[-0. -0. -0. ... -0. -0. -0.]
-0.0
-0.0
-1.0
-0.0
1.0
1.0

UPPER BOUND:
Primal: 0.4147999999999999
Duals:
-0.0
[-0. -0. -0. ... -0. -0. -0.]
[-0. -0. -0. ... -0. -0. -0.]
-0.0
-0.0
-1.0
-0.0
1.0
1.0


In [29]:
confounding_problem.read_data(raw=confounding_data.iloc[:1000], inference=True)

# add monotone-response assumptions (E[Y(d)|X=1] >= E[Y(d)|X=0] for d=0,1)
with respect_to(confounding_problem):
    turnout_if_college_in_highSES = E("Y(D=1)", cond="X=1")
    turnout_if_college_in_lowSES  = E("Y(D=1)", cond="X=0")
    turnout_if_nocollege_in_highSES = E("Y(D=0)", cond="X=1")
    turnout_if_nocollege_in_lowSES  = E("Y(D=0)", cond="X=0")

    add_assumption(turnout_if_college_in_highSES, '>=', turnout_if_college_in_lowSES)
    add_assumption(turnout_if_nocollege_in_highSES, '>=', turnout_if_nocollege_in_lowSES)

# solve LP and request inferential sampling
confounding_problem.solve(ci=True, nsamples=10)


Solving for point estimate bounds...
Point estimates

Dual: [0.0711822660098523, 0.831]
Primal: [0.0711822660098523, 0.831]
Generating samples:

Estimating CI: 


100%|██████████| 10/10 [00:06<00:00,  1.66it/s]

95% Confidence intervals. Lower: 0.02685643267048467,  Upper: 0.8451221241431386


{'point lb dual': 0.0711822660098523,
 'point ub dual': 0.831,
 'point lb primal': 0.0711822660098523,
 'point ub primal': 0.831,
 '2.5% lb bounds': np.float64(0.02685643267048467),
 '97.5% ub bounds': np.float64(0.8451221241431386),
 '1% lb bounds': np.float64(0.025055922818698728),
 '99% ub bounds': np.float64(0.8454641560815138)}

### Optimize the Dual

## Optimize only via the primal

In [30]:
import numpy as np
import pandas as pd
import torch

class ATEPrimalSolver:
    """
    Solves the primal linear program with gradient descent.
    Decision variables: p[x,d,y0,y1] for x,d,y0,y1 in {0,1}
    """

    def __init__(self, X, D, Y):
        """
        X, D, Y are numpy arrays of observed data
        """
        self.X = X
        self.D = D
        self.Y = Y

        # empirical joint P_obs(X=x, D=d, Y=y)
        self.q_obs = self._compute_observed_joint()

        # empirical marginal
        self.px = np.array([np.mean(X == 0), np.mean(X == 1)])

        # create trainable probabilities (16 variables)
        self.p = torch.nn.Parameter(
            torch.ones(2,2,2,2, dtype=torch.double) / 16,
            requires_grad=True
        )

        self.optimizer = torch.optim.Adam([self.p], lr=5e-2)

    # -----------------------------------------------------------
    def _compute_observed_joint(self):
        q = np.zeros((2,2,2))
        N = len(self.X)
        for x,d,y in zip(self.X, self.D, self.Y):
            q[x,d,y] += 1
        return q / N

    # -----------------------------------------------------------
    def _objective(self, maximize=False):
        """
        ATE = sum (y1 - y0) * p
        """
        y0 = torch.arange(2, dtype=torch.double)
        y1 = torch.arange(2, dtype=torch.double)
        Y0, Y1 = torch.meshgrid(y0, y1, indexing='ij')

        ATE = torch.sum((Y1 - Y0)[None,None,:,:] * self.p)

        return -ATE if maximize else ATE

    # -----------------------------------------------------------
    def _constraints_loss(self):
        loss = 0.0

        # (C1) observed joint constraints: sum_{y0,y1: y_d=y} p = q_obs
        for x in [0,1]:
            for d in [0,1]:
                for y in [0,1]:
                    mask = torch.zeros((2,2))
                    for y0 in [0,1]:
                        for y1 in [0,1]:
                            yd = y1 if d==1 else y0
                            if yd == y:
                                mask[y0,y1] = 1
                    loss += (torch.sum(self.p[x,d] * mask) - self.q_obs[x,d,y])**2

        # (C2) normalization
        loss += (torch.sum(self.p) - 1.0)**2

        # (C3) monotone-response:
        # E[Y(d)|X=1] >= E[Y(d)|X=0]
        for d in [0,1]:
            # LHS = p0 * E[Y(d)|X=1] - p1 * E[Y(d)|X=0]
            E1 = 0.0
            E0 = 0.0
            for d2 in [0,1]:
                for y0 in [0,1]:
                    for y1 in [0,1]:
                        yd = y1 if d==1 else y0
                        E1 += yd * self.p[1,d2,y0,y1]
                        E0 += yd * self.p[0,d2,y0,y1]

            lhs = self.px[0] * E1 - self.px[1] * E0
            loss += torch.relu(-lhs)   # penalty only if violated

        # (C2b) nonnegativity
        loss += torch.sum(torch.relu(-self.p))

        return loss

    # -----------------------------------------------------------
    def solve(self, maximize=False, iters=6000, l_constrained = 10):
        for it in range(iters):
            self.optimizer.zero_grad()
            loss = self._objective(maximize=maximize) + l_constrained * self._constraints_loss()
            loss.backward()
            self.optimizer.step()

            # project to >=0 to keep stable
            with torch.no_grad():
                self.p.data.clamp_(min=1e-9)
                # renormalize to keep mass ~1
                self.p.data /= self.p.data.sum()

        ATE_est = -self._objective(maximize=maximize).item() if maximize else self._objective().item()
        return ATE_est, self.p.data.clone()

# return upper and lower bounds
def solve_ATE_bounds(confounding_data, iters=6000):
    X = confounding_data["X"].values
    D = confounding_data["D"].values
    Y = confounding_data["Y"].values

    solver = ATEPrimalSolver(X, D, Y)

    lb, p_min = solver.solve(maximize=False, iters=iters, l_constrained=100)
    ub, p_max = solver.solve(maximize=True,  iters=iters, l_constrained=100)

    return {
        "ATE_lower": lb,
        "ATE_upper": ub,
        "p_min_solution": p_min,
        "p_max_solution": p_max,
    }

In [31]:
result = solve_ATE_bounds(confounding_data, iters=8000)

print("ATE lower bound =", result["ATE_lower"])
print("ATE upper bound =", result["ATE_upper"])

ATE lower bound = 0.14789582225275955
ATE upper bound = 0.7224395862362359


In [32]:
import numpy as np
import pandas as pd
import cvxpy as cp

# ---------------------------------------------------
# Prepare data
# ---------------------------------------------------
# Assume confounding_data with columns X,D,Y exists
X = confounding_data["X"].values
D = confounding_data["D"].values
Y = confounding_data["Y"].values
N = len(X)

# Compute observed joint P_obs(X,D,Y)
q_obs = np.zeros((2,2,2))
for x,d,y in zip(X,D,Y):
    q_obs[x,d,y] += 1
q_obs /= N

# Decision variables: p[x,d,y0,y1] for all 16 combinations
p = cp.Variable((2,2,2,2), nonneg=True)

# ---------------------------------------------------
# Build constraints
# ---------------------------------------------------
constraints = []

# (C1) observed joint: sum over y0,y1 where y_d = y
for x in [0,1]:
    for d in [0,1]:
        for y in [0,1]:
            mask = np.zeros((2,2))
            for y0 in [0,1]:
                for y1 in [0,1]:
                    yd = y1 if d==1 else y0
                    if yd == y:
                        mask[y0,y1] = 1
            constraints.append(cp.sum(cp.multiply(p[x,d], mask)) == q_obs[x,d,y])

# (C2) normalization
constraints.append(cp.sum(p) == 1)

# Monotone-response constraint: optional (skip for simplicity)
# constraints.append(...)

# ---------------------------------------------------
# Objective: ATE = E[Y|D=1] - E[Y|D=0]
# ---------------------------------------------------
ate_expr = 0
for x in [0,1]:
    for d in [0,1]:
        for y0 in [0,1]:
            for y1 in [0,1]:
                ate_expr += (y1 - y0) * p[x,d,y0,y1]

# ---------------------------------------------------
# Solve primal (min)
# ---------------------------------------------------
prob_min = cp.Problem(cp.Minimize(ate_expr), constraints)
prob_min.solve(solver=cp.GLPK)
print("PRIMAL LOWER BOUND:", prob_min.value)

# Print duals for each constraint
print("\nDUAL VARIABLES (minimization):")
for i,c in enumerate(constraints):
    try:
        print(f"Constraint {i}: dual = {c.dual_value}")
    except:
        print(f"Constraint {i}: dual = None")

# Solve primal (max)
prob_max = cp.Problem(cp.Maximize(ate_expr), constraints)
prob_max.solve(solver=cp.GLPK)
print("\nPRIMAL UPPER BOUND:", prob_max.value)

# Print duals for upper bound
print("\nDUAL VARIABLES (maximization):")
for i,c in enumerate(constraints):
    try:
        print(f"Constraint {i}: dual = {c.dual_value}")
    except:
        print(f"Constraint {i}: dual = None")


PRIMAL LOWER BOUND: -0.1679

DUAL VARIABLES (minimization):
Constraint 0: dual = -0.0
Constraint 1: dual = 1.0
Constraint 2: dual = 1.0
Constraint 3: dual = -0.0
Constraint 4: dual = -0.0
Constraint 5: dual = 1.0
Constraint 6: dual = 1.0
Constraint 7: dual = -0.0
Constraint 8: dual = -0.0

PRIMAL UPPER BOUND: 0.8321000000000001

DUAL VARIABLES (maximization):
Constraint 0: dual = -0.0
Constraint 1: dual = -1.0
Constraint 2: dual = -1.0
Constraint 3: dual = -0.0
Constraint 4: dual = -0.0
Constraint 5: dual = -1.0
Constraint 6: dual = -1.0
Constraint 7: dual = -0.0
Constraint 8: dual = 1.0


/usr/local/lib/python3.12/dist-packages/cvxpy/reductions/solvers/solving_chain_utils.py:41: UserWarning: The problem has an expression with dimension greater than 2. Defaulting to the SCIPY backend for canonicalization.
